name: convert-to-genai
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.12

  - conda-forge::pytorch==2.7.0
  - conda-forge::pytorch-gpu==2.7.0
  - conda-forge::gxx_linux-64

  - pip:
    - transformers
    - onnx
    - onnxruntime
    - onnxruntime-genai
    # need for cpu-int4-rtn-block-32
    - neural-compressor
    # fix neural-compressor dependency
    - "numpy>=2.2.0,<2.3.0"
    # need by transformers
    - tokenizers

    - gradio
