

services:
  convert-to-genai-gradio:
    image: xiaoyao9184/convert-to-genai:main
    environment:
      - SPACE_AUTHOR_NAME=xiaoyao9184
    ports:
      - "7860:7860"
    volumes:
      # - ./../../cache:/root/.cache
      # - ./../../models:/root/.genai-build/models
      # - ./../../logs:/root/.genai-build/logs
      - $HOME/.cache:/root/.cache
      - $HOME/.genai-build/models:/root/.genai-build/models
      - $HOME/.genai-build/logs:/root/.genai-build/logs
