

services:
  convert-to-genai-builder:
    image: xiaoyao9184/convert-to-genai:cpu-main
    command:
      - python3
      - -m
      - onnxruntime_genai.models.builder
      - -m
      - google/gemma-3-1b-it
      - -o
      - /root/.genai-build/models/convert-to-genai/gemma-3-1b-it-genai
      - -p
      - int4
      - -e
      - cpu
      - -c
      - /root/.cache/huggingface/hub
    environment:
      - HF_ENDPOINT=${HF_ENDPOINT:-https://huggingface.co}
      # NOTE: must set a token if the model requires granted access.
      - HF_TOKEN=${HF_TOKEN?error}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # - ./../../cache:/root/.cache
      - $HOME/.cache:/root/.cache
      - $HOME/.genai-build/models:/root/.genai-build/models
