

services:
  convert-to-genai-gradio:
    image: xiaoyao9184/convert-to-genai:cpu-main
    command: python3 /workspace/gradio/app.py
    environment:
      - HF_ENDPOINT=${HF_ENDPOINT:-https://huggingface.co}
      - HF_TOKEN=${HF_TOKEN:-}
      - SPACE_AUTHOR_NAME=${SPACE_AUTHOR_NAME:-}
      - CACHE_DIR=${C2G_CACHE_DIR:-${HUGGINGFACE_HUB_CACHE:-}}
      - OUTPUT_DIR=${C2G_OUTPUT_DIR:-}
      - LOG_DIR=${C2G_LOG_DIR:-}
      - IGNORE_CONVERTED=${C2G_IGNORE_CONVERTED:-}
      - IGNORE_ERRORS=${C2G_IGNORE_ERRORS:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "7860:7860"
    volumes:
      # - ./../../cache:/root/.cache
      # - ./../../models:/root/.genai-build/models
      # - ./../../logs:/root/.genai-build/logs
      - $HOME/.cache:/root/.cache
      - $HOME/.genai-build/models:/root/.genai-build/models
      - $HOME/.genai-build/logs:/root/.genai-build/logs
