

services:
  convert-to-genai-gradio:
    image: xiaoyao9184/convert-to-genai:cpu-main
    command: python3 /workspace/gradio/app.py
    environment:
      - HF_ENDPOINT=http://host.docker.internal:8090
      - SPACE_AUTHOR_NAME=xiaoyao9184
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "7860:7860"
    volumes:
      # - ./../../cache:/root/.cache
      # - ./../../models:/root/.genai-build/models
      # - ./../../logs:/root/.genai-build/logs
      - $HOME/.cache:/root/.cache
      - $HOME/.genai-build/models:/root/.genai-build/models
      - $HOME/.genai-build/logs:/root/.genai-build/logs
