
name: Docker Image Build/Publish tag with commit

on:
  push:
    branches:
      - 'main'
      - 'feature/arm64'
    paths:
      - gradio/**
      - docker/build.python@cpu/dockerfile
      - docker/build.pytorch@cuda/dockerfile
      - .github/workflows/docker-image-tag-commit.yml

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      # Fix github action 'No space left on device'
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get git short head
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 7

      - name: Meta data image(cpu)
        id: meta-cpu
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/convert-to-genai
            ghcr.io/${{ github.repository_owner }}/convert-to-genai
          tags: |
            type=raw,value=cpu-${{ github.ref_name }}
            type=raw,value=cpu-${{ steps.short-sha.outputs.sha }}
          flavor: |
            latest=false
          bake-target: cpu

      - name: Meta data image(cuda)
        id: meta-cuda
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/convert-to-genai
            ghcr.io/${{ github.repository_owner }}/convert-to-genai
          tags: |
            type=raw,value=cuda-${{ github.ref_name }}
            type=raw,value=cuda-${{ steps.short-sha.outputs.sha }}
          flavor: |
            latest=false
          bake-target: cuda

      - name: Build push image
        id: build
        uses: docker/bake-action@v6
        with:
          source: .
          files: |
            ./docker/docker-bake.hcl
            cwd://${{ steps.meta-cpu.outputs.bake-file-tags }}
            cwd://${{ steps.meta-cpu.outputs.bake-file-labels }}
            cwd://${{ steps.meta-cpu.outputs.bake-file-annotations }}
            cwd://${{ steps.meta-cuda.outputs.bake-file-tags }}
            cwd://${{ steps.meta-cuda.outputs.bake-file-labels }}
            cwd://${{ steps.meta-cuda.outputs.bake-file-annotations }}
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Print bake metadata
        run: echo "${{ steps.build.outputs.metadata }}"
